/*
-- Query: SELECT * FROM earthjoy.products
LIMIT 0, 1000

-- Date: 2022-01-26 02:58
*/
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (1,'Vivo y21','Phones','Made in Pakistan',75000,23,'Lets change the game','1.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (2,'Huawei Mate 40 Pro','Phones','Made in Pakistan',85000,12,'Huawei Mobiles','2.png',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (3,'Xiomi Redmi 10','Phones','Made in China',90000,12,'Xiomi Mobiles','3.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (4,'Samsung Y6','Tablets','Made in Pakistan',100000,14,'Samsung ','4.png',1,1,1,5,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (5,'Huawei Global','Tablets','Made in Pakistan',80000,7,'Huawei Mobiles','5.jpg',1,1,1,6,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (6,'Q Tab','Tablets','Made in Pakistan',40000,13,'Q Mobiles','6.jpg',1,1,1,10,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (7,'Dell Latitude E5440','Laptops','Made in Pakistan',80000,23,'Dell LTD','7.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (8,'Lenovo 3S','Laptops','Made in Pakistan',60000,7,'Lenovo LTD','8.jpg',1,1,1,13,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (9,'Dell DS4','Desktop','Made in Pakistan',70000,10,'Dell LTD','9.jpg',1,1,1,7,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (10,'HP 4S','Desktop','Made in Pakistan',40000,12,'HP LTD','10.jpg',1,1,1,2,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (11,'Nokia Camera','Cameras & Drones','Made in Japan',50000,4,'Nokia Company','11.jpg',1,1,1,2,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (12,'Samsung Drone','Cameras & Drones','Made in Pakistan',100000,13,'Samsung Mobiles','12.jpg',1,1,1,2,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (13,'Roku Watch','Smart Watches','Made in Pakistan',20000,20,'Dream Watch','13.jpg',1,1,1,7,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (14,'XBOX','Gaming Consoles','Made in Pakistan',60000,12,'Gaming Masterio','14.jpg',1,1,1,18,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (15,'PS4','Gaming Consoles','Made in Japan',20000,15,'Lets Play it.','15.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (16,'Samsung LED','Smart TV','Made in Pakistan',20000,13,'Samsung','16.jpg',1,1,1,5,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (17,'Haier LED','Smart TV','Made in China',10000,14,'Haier','17.jpg',1,1,1,9,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (18,'Stereo Speaker','Home Audio','Made in Pakistan',5000,2,'Stereo','18.jpg',1,1,1,7,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (19,'Presure Cooker','Kitchen Appliances','Made in Pakisttan',7000,3,'Enviro','19.jpg',1,1,1,7,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (20,'Harpic Floor Cleaner','Floor Care','Made in Pakistan',200,100,'Harpic','20.jpg',1,1,1,8,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (21,'Haier Generators','Generators','Made in Pakistan',1000,30,'Haier','21.jpg',1,1,1,6,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (22,'Washing Machine','Washers & Dryers','Made in Pakistan',10000,12,'Enviro','22.jpg',1,1,1,10,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (23,'Rose beauty Perfume','Fragrances','Made in Pakistan',5000,13,'Rose Beauty','23.jpg',1,1,1,9,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (24,'Hair dryer','Hair Care','Made in Pakistan',2000,12,'Enviro','24.jpg',1,1,1,10,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (25,'Beard Soap','Mens Care','Made in Pakistan',1000,13,'Darhi Mouch','25.jpg',1,1,1,13,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (26,'Fair & Handsome','Skin Care','Made in Pakistan',300,9,'Fair & Handsome','26.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (27,'Makeup kit','Makeup','Made in Pakisttan',500,21,'Bright & Beauty ','27.jpg',1,1,1,13,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (28,'Drip set','Medical Supplies','Made in Korea',200,25,'Heuko','28.jpg',1,1,1,13,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (29,'makeup machine','Beauty Tools','Made in Pakistan',400,24,'Bright & Beauty','29.jpg',1,1,1,12,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (30,'coke 1.5 liters','Bevarages','Made in Pakistan',100,982,'Coca Cola','30.jpg',1,1,1,9,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (31,'Cheese Cake','Fresh Products','Made in Pakistan',200,324,'Cakes & Bakes','31.jpg',1,1,1,14,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (32,'Kurleez','Snacks','Made in Pakistan',30,2072,'Kurleez','32.jpg',1,1,1,15,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (33,'Amm ka Muraba','Food Staples','Made in Lahore',100,34,'Bhai Muraba','33.jpg',1,1,1,14,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (34,'Ice Browny','Dairy & Chilled','Made in Pakistan',120,600,'Chocolisious','34.jpg',1,1,1,23,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (35,'Raho Fish','Frozen Food','Made in Pakistan',300,320,'Raho','35.jpg',1,1,1,34,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (36,'Jeans pent','Mens Fashon','Made in Pakistan',200,289,'Addidas','36.jpg',1,1,1,23,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (37,'Purse','Womens Fashon','Made in Pakistan',230,148,'Nike','37.jpg',1,1,1,14,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (38,'Jacket','Winter Clothing','Made in Pakistan',212,345,'Addidas','38.jpg',1,1,1,14,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (39,'T-Shirt','Summer Clothing','Made in Pakistan',200,398,'Addidas','39.jpg',1,1,1,14,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (40,'Under wear','Inner wear','Made in Pakistan',100,540,'Nike','40.jpg',1,1,1,15,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (41,'Sneaker','Shoes','Made in Pakistan',680,389,'Nike','41.jpg',1,1,1,18,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (42,'Tires','Accessories','Made in China',240,356,'Pak Wheels','42.jpg',1,1,1,21,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (43,'Honda 70','Motorcycles','Made in Pakistan',61000,23,'Honda','43.jpg',1,1,1,34,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (44,'Honda Civic','Cars','Made in Pakistan',1000000,12,'Honda','44.jpg',1,1,1,46,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (45,'Riksha - Yamaha','Rikshas','Made in China',45000,23,'Yamaha','45.jpg',1,1,1,47,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (46,'Trackter','Loaders','Made in Pakistan',65000,25,'Yamaha','46.jpg',1,1,1,23,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (47,'Heavy Bike','Sports Bikes','Made in Pakistan',900000,12,'Yamaha','47.jpg',1,1,1,29,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (48,'Helmet','Helmets','Made in Pakistan',500,25,'Honda','48.jpg',1,1,1,32,0);
INSERT INTO `` (`productId`,`pName`,`pType`,`pDescription`,`pPrice`,`pStock`,`pMainTag`,`pImages`,`pAppStatus`,`sellerId`,`aId`,`pClick`,`pblockStatus`) VALUES (49,'Face Cover Mask','Riding Gears','Made in Pakistan',300,25,'H&S','49.jpg',1,1,1,47,0);
